# Generated by Django 3.2.3 on 2021-07-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xray',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
