# Generated by Django 3.1.7 on 2021-10-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
