# Generated by Django 3.1.7 on 2021-10-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notification_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
