# Generated by Django 3.1.7 on 2021-10-18 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 54, 4, 602432)),
        ),
    ]
