# Generated by Django 3.2.3 on 2021-11-18 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211118_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
        ),
    ]
