# Generated by Django 3.2.3 on 2021-08-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
