# Generated by Django 3.2.3 on 2021-11-18 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(11, 36, 21, 219163)),
        ),
    ]
