# Generated by Django 3.2.3 on 2021-06-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_prescription_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
