# Generated by Django 3.2.3 on 2021-06-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_xray'),
    ]

    operations = [
        migrations.AddField(
            model_name='xray',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='xray',
            name='date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xray',
            name='image',
            field=models.ImageField(null=True, upload_to='Xrays/'),
        ),
        migrations.AddField(
            model_name='xray',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.AddField(
            model_name='xray',
            name='pic_id',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='xray',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.report'),
        ),
    ]
