# Generated by Django 3.2.3 on 2021-11-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
