# Generated by Django 3.2.3 on 2021-06-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210605_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xray',
            name='pic_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
