# Generated by Django 3.2.3 on 2021-06-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_xray_pic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xray',
            old_name='date',
            new_name='time',
        ),
    ]
