# Generated by Django 3.2.3 on 2021-06-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=5000)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.problem'),
        ),
    ]
