# Generated by Django 3.2.3 on 2021-07-16 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210620_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.problem'),
        ),
    ]
